### ISSUE TITLE
Support for dialogs

### ISSUE THREAD

**Issue by BenoitDuffez** [adil192/golden_screenshot#1]
This is awesome thanks.

I have a test that shows a dialog. Showing a dialog is actually navigating to a route, so I'm assuming that Flutter shows a new widget on top of the old one to display it.

I assume that as far as screenshots are concerned, the widget has not changed (the app under) so it does not show the dialog.

Do you have any idea how to support/display dialogs?

**Comment by BenoitDuffez** [comment]
Nevermind.

```finder: find.byType(ScreenshotApp)```

**Comment by BenoitDuffez** [comment]
Hm I closed too fast. When returning the `ScreenshotApp` widget it does show the dialog, however the canvas is 2400x1800 when the target device is 10 inch = 1920x1080.

The actual layout is full width but too high, with transparency top and bottom. I could crop this to 2400x1350 using image magick (`-trim +repage`). I had then to reach 1920x1080 (`-resize 80%`).

This works well on tablet or 10 inch (flatpak) however it does not work well on phones because the dialog uses the full canvas to dimension itself:

![image](https://github.com/user-attachments/assets/416f6988-8319-47a5-8345-acba2c2cfd7f)

So this technique (returning the `ScreenshotApp` widget) does not work that well.

Do you have another recommendation?

**Comment by adil192** [comment]
Please can you try with this in your `pubspec.yaml`...
```yaml
dependency_overrides:
  golden_screenshot:
    git:
      url: https://github.com/adil192/golden_screenshot
      ref: fitted-material-app
```
and without specifying a `finder`?

**Comment by BenoitDuffez** [comment]
Oh yes muuuuch better!!!

**Comment by adil192** [comment]
Perfect, you can now remove that dependency_override and use `golden_screenshot: ^2.1.0`

**Comment by BenoitDuffez** [comment]
Awesome. Thank you so much for this lib and the quick feature add for dialogs!!!
